import { Poppins } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";

const poppins=Poppins({weight:['100','200','300','400','500','600','700','800','900'],subsets:['latin']})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} overflow-x-hidden bg-gray-200`}>
        <main className="flex bg-gray-200 flex-col size-full h-full w-full">
          {/*NAVBAR*/}
          
         
            <Toaster/>
            {children}
          
        </main>
      </body>
    </html>
  );
}
